version: '3.7'

services:
  financial-database:
    image: postgres
    container_name: financial-database
    restart: always
    tty: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=financial-db
    networks:
      - financial-network
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
networks:
  financial-network:
    driver: bridge
